name: Generate UML Diagram
on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-uml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate PNG diagram
        uses: docker://plantuml/plantuml
        with:
          args: -tpng src/**/*.java -o diagrams
          
      - name: Commit and push diagram
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull
          git add attachment/*
          git commit -m "Update UML diagram [skip ci]" || echo "Sem alterações para commit"
          git push
