name: Generate UML
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate UML
        run: |
          docker run -v $PWD:/data plantuml/plantuml src/**/*.java
